### ISSUE TITLE
Error with Mosek in Julia 1.0.1

### ISSUE THREAD

**Issue by rodrigogarciana** [JuliaOpt/Mosek.jl#160]
Hi,
I updated this week to Julia 1.0 and I started having a problem with a simple conic model that I was previously solving with Mosek in Julia 0.6.4.
The same conic model is successfully solved by CPLEX 0.4.0 (v12.8) when I switch the solver.
I'm using Julia 1.0.1, JuMP 0.18.4 and Mosek 0.9.4

Below you will find the error message.

ERROR: MethodError: no method matching setindex_shape_check(::Boundkey, ::Int64)
Closest candidates are:
  setindex_shape_check(::AbstractArray{#s57,1} where #s57, ::Integer) at indices.jl:218
  setindex_shape_check(::AbstractArray{#s57,1} where #s57, ::Integer, ::Integer) at indices.jl:221
  setindex_shape_check(::AbstractArray{#s57,2} where #s57, ::Integer, ::Integer) at indices.jl:225
  ...

Thank you.

**Comment by blegat** [comment]
This error usually appears when you do broadcasting with something that does not implement `Base.broadcastable(x::X) = Ref(x)`. Can you give the line that gives you this error ? You may need to manually wrap something with `Ref`

**Comment by ulfworsoe** [comment]
I have fixed a few problems that might be related to this. Please check out branch `b0.9` and check if it works. If not, can you attach a small example or post the full trace?

**Comment by blegat** [comment]
Can you check that this is resolve in the branch `bl/fixassignscalarbroadcast` ?

**Comment by rodrigogarciana** [comment]
Hi @blegat 
I still receive the same error with b1/fixassignscalarbroadcast .
I'll pack the model into one file and attach it, in case it helps you understanding the problem better.
Thanks

**Comment by blegat** [comment]
@rodrigogarciana This is surprising, are you sure that you are using this branch ? What is `pathof(Mosek)` ? Have you done `] add Mosek#bl/fixassignscalarbroadcast` or `] dev Mosek` ?

**Comment by rodrigogarciana** [comment]
@blegat I've used `] add Mosek#bl/fixassignscalarbroadcast`   and the `pathof(Mosek)` is `"/home/s1523810/.julia/packages/Mosek/fZMxE/src/Mosek.jl"`
I'm attaching a picture with the information of the package versions I'm using and a ZIP file containing a mock-up example where I'm having this issue. (The same problem can be solved without any modifications by CPLEX).

Thanks again.

![mosekissue](https://user-images.githubusercontent.com/37311577/47013141-14af2400-d13e-11e8-8e4d-c8f5a4a05f00.png)
[MosekProblem.zip](https://github.com/JuliaOpt/Mosek.jl/files/2482778/MosekProblem.zip)

**Comment by blegat** [comment]
I think you need to restart the REPL, if you look at the error message, the error comes from `Mosek/pL1bl` which does not match with `pathof`

**Comment by rodrigogarciana** [comment]
Thank you @blegat, you are right with the new branch I needed to restart REPL, everything looks fine now (with branch bl/fix...). Do you know if these changes will be implemented in the master branch anytime soon? 
You were really helpful!
