### ISSUE TITLE
Installation issue/BinDeps

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/Mosek.jl#41]
Perhaps someone can help me shed some light on this.

I tried doing this (installing to a completely clean slate on linux x64, Ubuntu 14.04):
```
rm -rf ./juliapkg
export JULIA_PKGDIR=./juliapkg
julia -e 'Pkg.init(); Pkg.add("Mosek")'
```
Doing so produced this error:
```
================================[ ERROR: Mosek ]================================

LoadError: ArgumentError: BinDeps not found in path
while loading /home/ulfw/juliapkg/v0.4/Mosek/deps/build.jl, in expression starting on line 3

===============================================================================
```
I could see that BinDeps installed correctly before Mosek, and afterwards doing
```
julia -e 'using BinDeps'
```
produced no errors. However, 
```
julia -e 'Pkg.build("Mosek")'
```
consistently fails for me.

I am working on an non-BinDeps based installer, but I will have to either copy the download/unpack functions if I cannot import BinDeps.

@joehuchette @mlubin

**Comment by ulfworsoe** [comment]
Duplicate of issue #21

**Comment by ulfworsoe** [comment]
I am working on BinDeps-free installer. Code so far is here: https://github.com/ulfworsoe/Mosek.jl
When I have tested it a bit and can conclude that it mostly works I'll push it and our BinDeps woes will hopefully end.

**Comment by ulfworsoe** [comment]
I have pushed a new installer that does not use BinDeps. I have verified that the installer works (fetching MOSEK distro and unpacking) on linux x86 and amd64, Window svr 2012 amd64, OS X amd64. The installer requires external programs for unpacking (like BinDeps), which can be a problem on Windows.

**Comment by xiaoweiz** [comment]
@ulfworsoe  
Thanks for the fix! But I'm still having problem and there must be something I didn't do correctly. 

```julia
julia> Pkg.add("Mosek")
INFO: Installing Mosek v0.1.4
INFO: Building Mosek
================================[ ERROR: Mosek ]================================

None of the selected providers can install dependency libmosek.
Use BinDeps.debug(package_name) to see available providers

while loading /Users/xiaoweiz/.julia/v0.3/Mosek/deps/build.jl, in expression starting on line 87

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in /Users/xiaoweiz/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of Mosek
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> Pkg.checkout("Mosek")
INFO: Checking out Mosek master...
INFO: Pulling Mosek latest master...
INFO: No packages to install, update or remove

julia> using Mosek
ERROR: Mosek not properly installed. Please run Pkg.build("Mosek")
 in error at error.jl:21
 in include at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/xiaoweiz/.julia/v0.3/Mosek/src/Mosek.jl, in expression starting on line 5
```

**Comment by mlubin** [comment]
@xiaoweiz, what's the output of ``Pkg.build("Mosek")`` after ``Pkg.checkout("Mosek")``?

**Comment by ulfworsoe** [comment]
When you do clone/checkout it doesn't automatically build. You should run `Pkg.build("Mosek")` before using it.

**Comment by xiaoweiz** [comment]
Thanks for the reminder! After `Pkg.build("Mosek")`, it works like a charm.
